services:
  - type: web
    name: tms-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn job_portal.wsgi"
    envVars:
      - key: DEBUG
        value: False