# Generated by Django 4.2.11 on 2026-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
