# Generated by Django 4.2.11 on 2026-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_driver_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
