# Generated by Django 4.2.11 on 2026-03-20 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_accountprofile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All'), ('student', 'Students'), ('driver', 'Drivers')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=False),
        ),
    ]
