# Generated by Django 4.2.11 on 2026-03-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.student'),
        ),
    ]
